spring:
  datasource:
    url: jdbc:h2:mem:mong
    username: mong
    password:
    driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 730268131510-pptkovf90i55a79mf9o4te30mdq5qssv.apps.googleusercontent.com
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
            autorization-grant-type: authrization_code



jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHb11
